service:
  name: hack9-dashboard

plugins:
  - serverless-offline

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs10.x
  environment:
    DB_HOST: ${ssm:/hack9-dashboard/host}
    DB_USER: ${ssm:/hack9-dashboard/user}
    DB_PASSWORD: ${ssm:/hack9-dashboard/password}
    DB_DATABASE: ${ssm:/hack9-dashboard/database}

custom:
  serverless-offline:
    prefix: dev

functions:
  results:
    handler: src/handler.results
    events:
      - http:
          path: /results
          method: GET
  putApiUrl:
    handler: src/handler.putApiUrl
    events:
      - http:
          path: /teams/{teamId}/apiUrl
          method: PUT
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  postTestRequest:
    handler: src/handler.postTestRequest
    events:
      - http:
          path: /teams/{teamId}/testRequests
          method: POST
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  getTestRequest:
    handler: src/handler.getTestRequest
    events:
      - http:
          path: /testRequest
          method: GET
          request:
            parameters:
              querystrings:
                cloudProvider: false
                region: false  
  postTestResults:
    handler: src/handler.postTestResults
    events:
      - http:
          path: /testResults
          method: POST
  staticContent:
    handler: src/handler.staticContent
    events:
      - http: GET /
      - http: GET /{any+}
  preTokenGeneration:
    handler: src/handler.preTokenGeneration
    events:
      - cognitoUserPool:
          pool: hack9-2019
          trigger: PreTokenGeneration
          existing: true
