service:
  name: hack9-dashboard

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  stage: ${opt:stage, "test"}
  region: eu-west-1
  runtime: nodejs10.x
  environment:
    DB_HOST: localhost
    DB_USER: hack9
    DB_PASSWORD: hack9-2019
    DB_DATABASE: hack9-judge
    DEFAULT_PROVIDER: aws
    DEFAULT_REGION: eu-west-1

custom:
  serverless-offline:
    prefix: dev
  config:
    dev:
      dbHost: ${ssm:/hack9-dashboard-prod/host}
      dbUser: ${ssm:/hack9-dashboard-prod/user}
      dbPassword: ${ssm:/hack9-dashboard-prod/password}
      dbDatabase: ${ssm:/hack9-dashboard-prod/database}
    test:
      dbHost: ${ssm:/hack9-dashboard/host}
      dbUser: ${ssm:/hack9-dashboard/user}
      dbPassword: ${ssm:/hack9-dashboard/password}
      dbDatabase: ${ssm:/hack9-dashboard/database}

functions:
  results:
    handler: src/handler.getResults
    events:
      - http:
          path: /results
          method: GET
  getLatestExecutionpiUrl:
    handler: src/handler.getLatestExecution
    events:
      - http:
          path: /teams/{teamId}/executions/latest
          method: GET
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  getApiUrl:
    handler: src/handler.getApiUrl
    events:
      - http:
          path: /teams/{teamId}/apiUrl
          method: GET
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  putApiUrl:
    handler: src/handler.putApiUrl
    events:
      - http:
          path: /teams/{teamId}/apiUrl
          method: PUT
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  postTestRequest:
    handler: src/handler.postTestRequest
    events:
      - http:
          path: /teams/{teamId}/testRequests
          method: POST
          authorizer:
            arn:   arn:aws:cognito-idp:eu-west-1:745008152238:userpool/eu-west-1_VL4ON5eKr
  getTestRequest:
    handler: src/handler.getTestRequest
    events:
      - http:
          path: /testRequest
          method: GET
          request:
            parameters:
              querystrings:
                cloudProvider: false
                region: false  
  postTestResults:
    handler: src/handler.postTestResults
    events:
      - http:
          path: /testResults
          method: POST
  preTokenGeneration:
    handler: src/handler.preTokenGeneration
    events:
      - cognitoUserPool:
          pool: hack9-2019
          trigger: PreTokenGeneration
          existing: true
  calculateScores:
    handler: src/handler.calculateScores
    events:
      - schedule: cron(* * * * ? *)
      - http:
          path: /calculateRes
          method: GET
