INSERT INTO `team` (`id`, `name`, `api_url`, `score`, `cloud_provider`, `region`, `status`) VALUES
(1,'dev009',NULL,0.000,'aws','eu-west-1','ready'),
(2,'Epic Decomposition',NULL,0.000,'aws','eu-west-1','ready'),
(3,'Cloud Unicorns ','https://2019-hack9-reference-implementation.azurewebsites.net',0.000,'azure','westeurope','ready'),
(4,'It works on my cloud',NULL,0.000,'aws','eu-west-1','ready'),
(5,'No Cloud for Old Men',NULL,0.000,'azure','westeurope','ready'),
(6,'Teledvabisi',NULL,0.000,'aws','eu-west-1','ready'),
(7,'J-AWS Team',NULL,0.000,'aws','eu-west-1','ready'),
(8,'Fluffy Unicorns',NULL,0.000,'aws','eu-west-1','ready'),
(9,'The Cookie Byte',NULL,0.000,'aws','eu-west-1','ready'),
(10,'Stroopwafel and Coffee',NULL,0.000,'azure','westeurope','ready'),
(11,'ForCryingOutCloud',NULL,0.000,'azure','westeurope','ready'),
(12,'Karlovi Talenti',NULL,0.000,'azure','westeurope','ready'),
(13,'Mech''Clouds',NULL,0.000,'aws','eu-west-1','ready'),
(14,'BE-ton',NULL,0.000,'aws','eu-west-1','ready'),
(15,'cAPItans',NULL,0.000,'aws','eu-west-1','ready'),
(16,'Contractless',NULL,0.000,'aws','eu-west-1','ready'),
(17,'Kendo Masters Extreme ',NULL,0.000,'azure','westeurope','ready'),
(18,'Mali Mravi',NULL,0.000,'aws','eu-west-1','ready'),
(19,'Speed''n''Cloud',NULL,0.000,'aws','eu-west-1','ready'),
(20,'WYSIWYG’s',NULL,0.000,'aws','eu-west-1','ready'),
(21,'MobileZ',NULL,0.000,'aws','eu-west-1','ready'),
(22,'W-team ',NULL,0.000,'aws','eu-west-1','ready'),
(23,'Rockstars',NULL,0.000,'azure','westeurope','ready'),
(24,'Much Speed Such Service',NULL,0.000,'azure','westeurope','ready'),
(25,'Hahaton',NULL,0.000,'aws','eu-west-1','ready'),
(26,'Season Salad',NULL,0.000,'azure','westeurope','ready'),
(27,'JustAnotherTeam',NULL,0.000,'aws','eu-west-1','ready'),
(28,'hAPI9',NULL,0.000,'aws','eu-west-1','ready'),
(29,'The Fixers',NULL,0.000,'aws','eu-west-1','ready'),
(30,'Mix & Fix',NULL,0.000,'azure','westeurope','ready'),
(31,'UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS',NULL,0.000,'aws','eu-west-1','ready'),
(32,'Frontpage',NULL,0.000,'azure','westeurope','ready'),
(33,'MS Haccess',NULL,0.000,'azure','westeurope','ready'),
(34,'Judges','http://ec2-52-50-206-210.eu-west-1.compute.amazonaws.com:8080/reference',0.000,'aws','eu-west-1','ready');

INSERT INTO `user` (`id`, `name`, `email`, `team_id`, `type`) VALUES
(1,'Miloš Jovanović','m.jovanovic@example.com',34,'admin'),
(2,'Dragan Gajić','d.gajic@example.com',34,'admin'),
(3,'Nikola Milutinović','n.milutinovic@example.com',34,'admin'),
(4,'Dragana Momčilović','d.momcilovic@example.com',34,'admin'),
(5,'Mirjana Kolarov','mi.kolarov@example.com',34,'admin'),
(6,'Dmytro Panin','d.panin@example.com',34,'admin'),
(7,'Ionut Stanescu','i.stanescu@example.com',34,'admin'),
(8,'Milos Radojcic','m.radojcic@example.com',1,'user'),
(9,'Mateja Asanin','m.asanin@example.com',1,'user'),
(10,'Milos Milutinovic','m.milutinovic@example.com',1,'user'),
(11,'Nikola Komazec','n.komazec@example.com',1,'user'),
(12,'Milica Panic','m.panic@example.com',1,'user'),
(13,'Vladimir Cepulja','v.crepulja@example.com',1,'user'),
(14,'Olena Goncharenko ','o.goncharenko@example.com',2,'user'),
(15,'evgenii Kuchanskyi','i.kuchanskyi@example.com',2,'user'),
(16,'Yevhen Chychkan','y.chychkan@example.com',2,'user'),
(17,'Yurii Tatur','y.tatur@example.com',2,'user'),
(18,'Mykhailo Melnyk','m.melnyk@example.com',2,'user'),
(19,'Ihor Kozlov','i.kozlov@example.com',2,'user'),
(20,'Ionut Vasiliu','i.vasiliu@example.com',3,'user'),
(21,'Mihaela Radulescu','m.radulescu@example.com',3,'user'),
(22,'Alecsandru Neculai Andrei','a.andrei@example.com',3,'user'),
(23,'Danuzia Elena Anusca','d.anusca@example.com',3,'user'),
(24,' Sorin Pavel','s.pavel@example.com',3,'user'),
(25,'Codrin Baleanu','c.baleanu@example.com',3,'user'),
(26,'Filip Stajkovic','f.stajkovic@example.com',4,'user'),
(27,'Lazar Veljovic','l.veljovic@example.com',4,'user'),
(28,'Svetislav Marjanovic','s.marjanovic@example.com',4,'user'),
(29,'Petar Damjanovic','p.damjanovic@example.com',4,'user'),
(30,'Marko Suker','m.suker@example.com',4,'user'),
(31,'Dragana Stankovic','d.stankovic@example.com',5,'user'),
(32,'Igor Dragutinovic','i.dragutinovic@example.com',5,'user'),
(33,'Marko Knezevic','ma.knezevic@example.com',5,'user'),
(34,'Dalibor Kovacevic','d.kovacevic@example.com',5,'user'),
(35,'Stefan Djordjevic','s.djordjevic@example.com',5,'user'),
(36,'Marko Acanski','m.acanski@example.com',5,'user'),
(37,'Dragan Dukic','d.dukic@example.com',6,'user'),
(38,'Marko Djakovic','m.djakovic@example.com',6,'user'),
(39,'Jovana Milanovic','j.milanovic@example.com',6,'user'),
(40,'Uros Gmizic','u.gmizic@example.com',6,'user'),
(41,'Stefan Halapa','s.halapa@example.com',6,'user'),
(42,'David Vuletas','d.vuletas@example.com',6,'user'),
(43,'Andrii Hrytsiuk','a.hrytsiuk@example.com',7,'user'),
(44,'Olha Karpenko','o.karpenko@example.com',7,'user'),
(45,'Oleksandr Hladun','o.hladun@example.com',7,'user'),
(46,'Denys Shmyhin','d.shmyhin@example.com',7,'user'),
(47,'Oleksandr Opanasiuk','o.opanasiuk@example.com',7,'user'),
(48,'Viktor Palyushok','v.palyushok@example.com',7,'user'),
(49,'Nemanja Mitic','n.mitic@example.com',8,'user'),
(50,'Ana Milovanovic','a.milovanovic@example.com',8,'user'),
(51,'Zeljko Turbic','z.turbic@example.com',8,'user'),
(52,'Ivan Sardelic','i.sardelic@example.com',8,'user'),
(53,'Vladimir Radojkovic','v.radojkovic@example.com',8,'user'),
(54,'Olivera Gavrilovic','o.gavrilovic@example.com',8,'user'),
(55,'Vuk Stankovic','v.stankovic@example.com',8,'user'),
(56,'Dejan Belic','d.belic@example.com',9,'user'),
(57,'Nemanja Rajkovic','n.rajkovic@example.com',9,'user'),
(58,'Jovan Zivanov','j.zivanov@example.com',9,'user'),
(59,'Andrej Kamikovski','a.kamikovski@example.com',10,'user'),
(60,'Dalibor Takac','da.takac@example.com',10,'user'),
(61,'Stefan Milankov','s.milankov@example.com',10,'user'),
(62,'Jovan Dimic','j.dimic@example.com',10,'user'),
(63,'Milan Kojadinovic','m.kojadinovic@example.com',10,'user'),
(64,'Marko Dmitrovic','m.dmitrovic@example.com',11,'user'),
(65,'Nikola Jovanovic','n.jovanovic@example.com',11,'user'),
(66,'Katarina Ivosevic','k.ivosevic@example.com',11,'user'),
(67,'Marko Antonic','m.antonic@example.com',11,'user'),
(68,'Nevena Kovacevic','n.kovacevic@example.com',11,'user'),
(69,'Marko Bilic','m.bilic@example.com',11,'user'),
(70,'Milan Kablar','m.kablar@example.com',12,'user'),
(71,'Boris Matijasevic','b.matijasevic@example.com',12,'user'),
(72,'Nenad Misic','n.misic@example.com',12,'user'),
(73,'Srdjan Subotic','s.subotic@example.com',12,'user'),
(74,'Nemanja Arsic','n.arsic@example.com',12,'user'),
(75,'Kosta Sotic','k.sotic@example.com',12,'user'),
(76,'Miro Zorboski','m.zorboski@example.com',13,'user'),
(77,'Nina Stanic','n.stanic@example.com',13,'user'),
(78,'Aleksandar Vlaskalic','a.vlaskalic@example.com',13,'user'),
(79,'Dragan Nastic','d.nastic@example.com',13,'user'),
(80,'Ivan Jakovljevic','i.jakovljevic@example.com',13,'user'),
(81,'Dejan Zlataric','d.zlataric@example.com',13,'user'),
(82,'Stevan Kosijer','s.kosijer@example.com',13,'user'),
(83,'Anton Krekotun','a.krekotun@example.com',14,'user'),
(84,'Igor Tananika','i.tananika@example.com',14,'user'),
(85,'Sergii Rumiantsev','s.rumiantsev@example.com',14,'user'),
(86,'Vladislav Snitsar','v.snitsar@example.com',14,'user'),
(87,'Anna Bondarchuk','a.bondarchuk@example.com',14,'user'),
(88,'Oleksandr Martynenko','o.martynenko@example.com',14,'user'),
(89,'Ivan Nikolaievskyi','i.nikolaievskyi@example.com',14,'user'),
(90,'Olga Bondar','o.bondar@example.com',15,'user'),
(91,'Yevhen Bessarabov','y.bessarabov@example.com',15,'user'),
(92,'Kostiantyn Synyshyn','k.synyshyn@example.com',15,'user'),
(93,'Oleksandr Rybak','o.rybak@example.com',15,'user'),
(94,'Dmytro Yesepchuk','d.yesepchuk@example.com',15,'user'),
(95,'Denys Riaguzov','d.riaguzov@example.com',15,'user'),
(96,'Iryna Iurchuk','i.iurchuk@example.com',15,'user'),
(97,'Dusan Dimitric','d.dimitric@example.com',16,'user'),
(98,'Milos Dodovic','m.dodovic@example.com',16,'user'),
(99,'Nebojsa Loznjakovic','n.loznjakovic@example.com',16,'user'),
(100,'Gordana Gardic','g.gardic@example.com',16,'user'),
(101,'Dusan Veljovic','d.veljovic@example.com',16,'user'),
(102,'Filip Pausic','f.pausic@example.com',17,'user'),
(103,'Marko Vajs','m.vajs@example.com',17,'user'),
(104,'Ivan Kukic','i.kukic@example.com',17,'user'),
(105,'Cedomir Ribic','c.ribic@example.com',17,'user'),
(106,'Marko Popovic','ma.popovic@example.com',17,'user'),
(107,'Djordje Nikolic','dj.nikolic@example.com',17,'user'),
(108,'Damir Nonkovic','d.nonkovic@example.com',17,'user'),
(109,'Aleksandar Kiselicki','a.kiselicki@example.com',18,'user'),
(110,'Boris Demir','b.demir@example.com',18,'user'),
(111,'Sasa Dobrilovic','s.dobrilovic@example.com',18,'user'),
(112,'Petar Jovanovic','p.jovanovic@example.com',18,'user'),
(113,'Gabriel Patras','g.patras@example.com',19,'user'),
(114,'Iustinian Dominte','i.dominte@example.com',19,'user'),
(115,'Loredana Lehadus','l.lehadus@example.com',19,'user'),
(116,'Mihai Sitaru','m.sitaru@example.com',19,'user'),
(117,'Razvan Manole','r.manole@example.com',19,'user'),
(118,'Sorin Radu','s.radu@example.com',19,'user'),
(119,'Victor Munteanu','v.munteanu@example.com',19,'user'),
(120,'Petar Lalosevic','p.lalosevic@example.com',20,'user'),
(121,'Nikola Nikic','n.nikic@example.com',20,'user'),
(122,'Milan Savic','mi.savic@example.com',20,'user'),
(123,'Dusan Radovic','d.radovic@example.com',20,'user'),
(124,'Jelena Dubovi','j.dubovi@example.com',20,'user'),
(125,'Igor Dedic','i.dedic@example.com',20,'user'),
(126,'Nemanja Smiljanic','n.smiljanic@example.com',20,'user'),
(127,'Marijana Gligoric','m.gligoric@example.com',21,'user'),
(128,'Teodora Garasanin','t.garasanin@example.com',21,'user'),
(129,'Srdjan Ristanovic','s.ristanovic@example.com',21,'user'),
(130,'Ognjen Manevski','o.manevski@example.com',21,'user'),
(131,'Alexandra Mircea','a.mircea@example.com',22,'user'),
(132,'Ramona Farcas','r.farcas@example.com',22,'user'),
(133,'Lucian Ailenei','l.ailenei@example.com',22,'user'),
(134,'Ciprian Sofronia','c.sofronia@example.com',22,'user'),
(135,'Ionut Ovidiu Galatanu','i.galatanu@example.com',22,'user'),
(136,'Flavius Condrea','f.condrea@example.com',22,'user'),
(137,'Iulian Constantinescu','i.constantinescu@example.com',22,'user'),
(138,'Borislav Ervacanin','b.ervacanin@example.com',23,'user'),
(139,'Mirko Horvacki','m.horvacki@example.com',23,'user'),
(140,'Marko Mitic','m.mitic@example.com',23,'user'),
(141,'Simonida Kadic','s.kadic@example.com',23,'user'),
(142,'Djordje Filipovic','dj.filipovic@example.com',23,'user'),
(143,'Nina Bjelobaba','n.bjelobaba@example.com',23,'user'),
(144,'Ancuta Costan','a.costan@example.com',24,'user'),
(145,'Mariana Dumitriu','m.dumitriu@example.com',24,'user'),
(146,'Cristiana Antalut','c.antalut@example.com',24,'user'),
(147,'Radu Iscu','r.iscu@example.com',24,'user'),
(148,'Mircea Serediuc','m.serediuc@example.com',24,'user'),
(149,'Radu Vulpescu','r.vulpescu@example.com',24,'user'),
(150,'Constantin Oniga','c.oniga@example.com',24,'user'),
(151,'Sofija Bojic','s.bojic@example.com',25,'user'),
(152,'Goran Gizarovski','g.gizarovski@example.com',25,'user'),
(153,'Vanja Al-Halidi','v.al-halidi@example.com',25,'user'),
(154,'Zeljko Simic','z.simic@example.com',25,'user'),
(155,'Milan Urukalo','m.urukalo@example.com',25,'user'),
(156,'Boban Piskulic','b.piskulic@example.com',25,'user'),
(157,'Stanislav Ivanovic','s.ivanovic@example.com',26,'user'),
(158,'Slavko Bukvic','s.bukvic@example.com',26,'user'),
(159,'Bratislav Baljak','b.baljak@example.com',26,'user'),
(160,'Slobodan Dan','s.dan@example.com',26,'user'),
(161,'Zolt Varga','z.varga@example.com',26,'user'),
(162,'Dusan Munjiza','d.munjiza@example.com',26,'user'),
(163,'Oleksandr Odarchenko','o.odarchenko@example.com',27,'user'),
(164,'Orest Borovyi','o.borovyi@example.com',27,'user'),
(165,'Roman Datsyuk','r.datsyuk@example.com',27,'user'),
(166,'Yuriy Hulpa','y.hulpa@example.com',27,'user'),
(167,'Mykhailo Shchetinin','m.shchetinin@example.com',27,'user'),
(168,'Andrii Dumyn','a.dumyn@example.com',27,'user'),
(169,'Yevhen Sirotin','y.sirotin@example.com',28,'user'),
(170,'Roman Solodkyi','r.solodkyi@example.com',28,'user'),
(171,'Viktoria Golieusova','v.golieusova@example.com',28,'user'),
(172,'Aliia Ibragimova','a.ibragimova@example.com',28,'user'),
(173,'Oleh Fedianovych','o.fedianovych@example.com',28,'user'),
(174,'Mark Salabutin','m.salabutin@example.com',28,'user'),
(175,'Maksym Penderuk','m.penderuk@example.com',28,'user'),
(176,'Roman Kniazevych','r.kniazevych@example.com',29,'user'),
(177,'Volodymyr Shalimov','v.shalimov@example.com',29,'user'),
(178,'Oleh Koval','o.koval@example.com',29,'user'),
(179,'Mykhailo Kaminetskyi','m.kaminetskyi@example.com',29,'user'),
(180,'Roman Vitruk','r.vitruk@example.com',29,'user'),
(181,'Iulia Sargu','i.sargu@example.com',30,'user'),
(182,'Teodora Elena Timcu','t.timcu@example.com',30,'user'),
(183,'Adrian Ghitu','a.ghitu@example.com',30,'user'),
(184,'Marius Mihai Nastase','m.nastase@example.com',30,'user'),
(185,'Bianca Iuliana Bulai','b.bulai@example.com',30,'user'),
(186,'Andrei Pintilie','a.pintilie@example.com',30,'user'),
(187,'Dragos Tiganescu','d.tiganescu@example.com',30,'user'),
(188,'Aleksandar Gradina','a.gradina@example.com',31,'user'),
(189,'Boban Poznanovic','b.poznanovic@example.com',31,'user'),
(190,'Davor Ceman','d.ceman@example.com',31,'user'),
(191,'Miroslav Kospic','m.kospic@example.com',31,'user'),
(192,'Nikola Janicijevic','n.janicijevic@example.com',31,'user'),
(193,'Nikola Kolosnjaji','n.kolosnjaji@example.com',31,'user'),
(194,'Nikola Milic','n.milic@example.com',31,'user'),
(195,'Djordje Kalanj','dj.kalanj@example.com',32,'user'),
(196,'Sasa Malezic','s.malezic@example.com',32,'user'),
(197,'Marko Bradonjic','m.bradonjic@example.com',32,'user'),
(198,'Vidak Kavedzic','v.kavedzic@example.com',32,'user'),
(199,'Nikola Milinkovic','n.milinkovic@example.com',32,'user'),
(200,'Nikola B Nedeljkovic','nb.nedeljkovic@example.com',32,'user'),
(201,'Aleksandar Krstic','al.krstic@example.com',33,'user'),
(202,'Miro Kalajdzic','m.kalajdzic@example.com',33,'user'),
(203,'Vladan Vojimirovic','v.vojimirovic@example.com',33,'user'),
(204,'Nemanja Gladovic','n.gladovic@example.com',33,'user'),
(205,'Nenad Domuz','n.domuz@example.com',33,'user'),
(206,'Stefan Krstic','s.krstic@example.com',33,'user');
