INSERT INTO `team` VALUES
(1,'dev009',NULL,0.000,'aws','eu-west-1','ready'),
(2,'Epic Decomposition',NULL,0.000,'aws','eu-west-1','ready'),
(3,'Cloud Unicorns ','https://2019-hack9-reference-implementation.azurewebsites.net',0.000,'azure','eu-west-1','ready'),
(4,'It works on my cloud',NULL,0.000,'aws','eu-west-1','ready'),
(5,'No Cloud for Old Men',NULL,0.000,'azure','West US 2','ready'),
(6,'Teledvabisi',NULL,0.000,'aws','eu-west-1','ready'),
(7,'J-AWS Team',NULL,0.000,'aws','eu-west-1','ready'),
(8,'Fluffy Unicorns',NULL,0.000,'aws','eu-west-1','ready'),
(9,'The Cookie Byte',NULL,0.000,'aws','eu-west-1','ready'),
(10,'Stroopwafel and Coffee',NULL,0.000,'azure','West US 2','ready'),
(11,'ForCryingOutCloud',NULL,0.000,'azure','West US 2','ready'),
(12,'Karlovi Talenti',NULL,0.000,'azure','West US 2','ready'),
(13,'Mech''Clouds',NULL,0.000,'aws','eu-west-1','ready'),
(14,'BE-ton',NULL,0.000,'aws','eu-west-1','ready'),
(15,'cAPItans',NULL,0.000,'aws','eu-west-1','ready'),
(16,'Contractless',NULL,0.000,'aws','eu-west-1','ready'),
(17,'Kendo Masters Extreme ',NULL,0.000,'azure','West US 2','ready'),
(18,'Mali Mravi',NULL,0.000,'aws','eu-west-1','ready'),
(19,'Speed''n''Cloud',NULL,0.000,'aws','eu-west-1','ready'),
(20,'WYSIWYG’s',NULL,0.000,'aws','eu-west-1','ready'),
(21,'MobileZ',NULL,0.000,'aws','eu-west-1','ready'),
(22,'W-team ',NULL,0.000,'aws','eu-west-1','ready'),
(23,'Rockstars',NULL,0.000,'azure','West US 2','ready'),
(24,'Much Speed Such Service',NULL,0.000,'azure','West US 2','ready'),
(25,'Hahaton',NULL,0.000,'aws','eu-west-1','ready'),
(26,'Season Salad',NULL,0.000,'azure','West US 2','ready'),
(27,'JustAnotherTeam',NULL,0.000,'aws','eu-west-1','ready'),
(28,'hAPI9',NULL,0.000,'aws','eu-west-1','ready'),
(29,'The Fixers',NULL,0.000,'aws','eu-west-1','ready'),
(30,'Mix & Fix',NULL,0.000,'azure','West US 2','ready'),
(31,'UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS',NULL,0.000,'aws','eu-west-1','ready'),
(32,'Frontpage',NULL,0.000,'azure','West US 2','ready'),
(33,'MS Haccess',NULL,0.000,'azure','West US 2','ready'),
(34,'Judges','http://ec2-52-50-206-210.eu-west-1.compute.amazonaws.com:8080/reference',0.000,'aws','eu-west-1','ready');

INSERT INTO `user` VALUES
(1,'Miloš Jovanović','m.jovanovic@levi9.com',34,'admin'),
(2,'Dragan Gajić','d.gajic@levi9.com',34,'admin'),
(3,'Nikola Milutinović','n.milutinovic@levi9.com',34,'admin'),
(4,'Dragana Momčilović','d.momcilovic@levi9.com',34,'admin'),
(5,'Mirjana Kolarov','mi.kolarov@levi9.com',34,'admin'),
(6,'Dmytro Panin','d.panin@levi9.com',34,'admin'),
(7,'Ionut Stanescu','i.stanescu@levi9.com',34,'admin'),
(8,'Milos Radojcic','m.radojcic@levi9.com',1,'user'),
(9,'Mateja Asanin','m.asanin@levi9.com',1,'user'),
(10,'Milos Milutinovic','m.milutinovic@levi9.com',1,'user'),
(11,'Nikola Komazec','n.komazec@levi9.com',1,'user'),
(12,'Milica Panic','m.panic@levi9.com',1,'user'),
(13,'Vladimir Cepulja','v.crepulja@levi9.com',1,'user'),
(14,'Olena Goncharenko ','o.goncharenko@levi9.com',2,'user'),
(15,'evgenii Kuchanskyi','i.kuchanskyi@levi9.com',2,'user'),
(16,'Yevhen Chychkan','y.chychkan@levi9.com',2,'user'),
(17,'Yurii Tatur','y.tatur@levi9.com',2,'user'),
(18,'Mykhailo Melnyk','m.melnyk@levi9.com',2,'user'),
(19,'Ihor Kozlov','i.kozlov@levi9.com',2,'user'),
(20,'Ionut Vasiliu','i.vasiliu@levi9.com',3,'user'),
(21,'Mihaela Radulescu','m.radulescu@levi9.com',3,'user'),
(22,'Alecsandru Neculai Andrei','a.andrei@levi9.com',3,'user'),
(23,'Danuzia Elena Anusca','d.anusca@levi9.com',3,'user'),
(24,' Sorin Pavel','s.pavel@levi9.com',3,'user'),
(25,'Codrin Baleanu','c.baleanu@levi9.com',3,'user'),
(26,'Filip Stajkovic','f.stajkovic@levi9.com',4,'user'),
(27,'Lazar Veljovic','l.veljovic@levi9.com',4,'user'),
(28,'Svetislav Marjanovic','s.marjanovic@levi9.com',4,'user'),
(29,'Petar Damjanovic','p.damjanovic@levi9.com',4,'user'),
(30,'Marko Suker','m.suker@levi9.com',4,'user'),
(31,'Dragana Stankovic','d.stankovic@levi9.com',5,'user'),
(32,'Igor Dragutinovic','i.dragutinovic@levi9.com',5,'user'),
(33,'Marko Knezevic','ma.knezevic@levi9.com',5,'user'),
(34,'Dalibor Kovacevic','d.kovacevic@levi9.com',5,'user'),
(35,'Stefan Djordjevic','s.djordjevic@levi9.com',5,'user'),
(36,'Marko Acanski','m.acanski@levi9.com',5,'user'),
(37,'Dragan Dukic','d.dukic@levi9.com',6,'user'),
(38,'Marko Djakovic','m.djakovic@levi9.com',6,'user'),
(39,'Jovana Milanovic','j.milanovic@levi9.com',6,'user'),
(40,'Uros Gmizic','u.gmizic@levi9.com',6,'user'),
(41,'Stefan Halapa','s.halapa@levi9.com',6,'user'),
(42,'David Vuletas','d.vuletas@levi9.com',6,'user'),
(43,'Andrii Hrytsiuk','a.hrytsiuk@levi9.com',7,'user'),
(44,'Olha Karpenko','o.karpenko@levi9.com',7,'user'),
(45,'Oleksandr Hladun','o.hladun@levi9.com',7,'user'),
(46,'Denys Shmyhin','d.shmyhin@levi9.com',7,'user'),
(47,'Oleksandr Opanasiuk','o.opanasiuk@levi9.com',7,'user'),
(48,'Viktor Palyushok','v.palyushok@levi9.com',7,'user'),
(49,'Nemanja Mitic','n.mitic@levi9.com',8,'user'),
(50,'Ana Milovanovic','a.milovanovic@levi9.com',8,'user'),
(51,'Zeljko Turbic','z.turbic@levi9.com',8,'user'),
(52,'Ivan Sardelic','i.sardelic@levi9.com',8,'user'),
(53,'Vladimir Radojkovic','v.radojkovic@levi9.com',8,'user'),
(54,'Olivera Gavrilovic','o.gavrilovic@levi9.com',8,'user'),
(55,'Vuk Stankovic','v.stankovic@levi9.com',8,'user'),
(56,'Dejan Belic','d.belic@levi9.com',9,'user'),
(57,'Nemanja Rajkovic','n.rajkovic@levi9.com',9,'user'),
(58,'Jovan Zivanov','j.zivanov@levi9.com',9,'user'),
(59,'Andrej Kamikovski','a.kamikovski@levi9.com',10,'user'),
(60,'Dalibor Takac','da.takac@levi9.com',10,'user'),
(61,'Stefan Milankov','s.milankov@levi9.com',10,'user'),
(62,'Jovan Dimic','j.dimic@levi9.com',10,'user'),
(63,'Milan Kojadinovic','m.kojadinovic@levi9.com',10,'user'),
(64,'Marko Dmitrovic','m.dmitrovic@levi9.com',11,'user'),
(65,'Nikola Jovanovic','n.jovanovic@levi9.com',11,'user'),
(66,'Katarina Ivosevic','k.ivosevic@levi9.com',11,'user'),
(67,'Marko Antonic','m.antonic@levi9.com',11,'user'),
(68,'Nevena Kovacevic','n.kovacevic@levi9.com',11,'user'),
(69,'Marko Bilic','m.bilic@levi9.com',11,'user'),
(70,'Milan Kablar','m.kablar@levi9.com',12,'user'),
(71,'Boris Matijasevic','b.matijasevic@levi9.com',12,'user'),
(72,'Nenad Misic','n.misic@levi9.com',12,'user'),
(73,'Srdjan Subotic','s.subotic@levi9.com',12,'user'),
(74,'Nemanja Arsic','n.arsic@levi9.com',12,'user'),
(75,'Kosta Sotic','k.sotic@levi9.com',12,'user'),
(76,'Miro Zorboski','m.zorboski@levi9.com',13,'user'),
(77,'Nina Stanic','n.stanic@levi9.com',13,'user'),
(78,'Aleksandar Vlaskalic','a.vlaskalic@levi9.com',13,'user'),
(79,'Dragan Nastic','d.nastic@levi9.com',13,'user'),
(80,'Ivan Jakovljevic','i.jakovljevic@levi9.com',13,'user'),
(81,'Dejan Zlataric','d.zlataric@levi9.com',13,'user'),
(82,'Stevan Kosijer','s.kosijer@levi9.com',13,'user'),
(83,'Anton Krekotun','a.krekotun@levi9.com',14,'user'),
(84,'Igor Tananika','i.tananika@levi9.com',14,'user'),
(85,'Sergii Rumiantsev','s.rumiantsev@levi9.com',14,'user'),
(86,'Vladislav Snitsar','v.snitsar@levi9.com',14,'user'),
(87,'Anna Bondarchuk','a.bondarchuk@levi9.com',14,'user'),
(88,'Oleksandr Martynenko','o.martynenko@levi9.com',14,'user'),
(89,'Ivan Nikolaievskyi','i.nikolaievskyi@levi9.com',14,'user'),
(90,'Olga Bondar','o.bondar@levi9.com',15,'user'),
(91,'Yevhen Bessarabov','y.bessarabov@levi9.com',15,'user'),
(92,'Kostiantyn Synyshyn','k.synyshyn@levi9.com',15,'user'),
(93,'Oleksandr Rybak','o.rybak@levi9.com',15,'user'),
(94,'Dmytro Yesepchuk','d.yesepchuk@levi9.com',15,'user'),
(95,'Denys Riaguzov','d.riaguzov@levi9.com',15,'user'),
(96,'Iryna Iurchuk','i.iurchuk@levi9.com',15,'user'),
(97,'Dusan Dimitric','d.dimitric@levi9.com',16,'user'),
(98,'Milos Dodovic','m.dodovic@levi9.com',16,'user'),
(99,'Nebojsa Loznjakovic','n.loznjakovic@levi9.com',16,'user'),
(100,'Gordana Gardic','g.gardic@levi9.com',16,'user'),
(101,'Dusan Veljovic','d.veljovic@levi9.com',16,'user'),
(102,'Filip Pausic','f.pausic@levi9.com',17,'user'),
(103,'Marko Vajs','m.vajs@levi9.com',17,'user'),
(104,'Ivan Kukic','i.kukic@levi9.com',17,'user'),
(105,'Cedomir Ribic','c.ribic@levi9.com',17,'user'),
(106,'Marko Popovic','ma.popovic@levi9.com',17,'user'),
(107,'Djordje Nikolic','dj.nikolic@levi9.com',17,'user'),
(108,'Damir Nonkovic','d.nonkovic@levi9.com',17,'user'),
(109,'Aleksandar Kiselicki','a.kiselicki@levi9.com',18,'user'),
(110,'Boris Demir','b.demir@levi9.com',18,'user'),
(111,'Sasa Dobrilovic','s.dobrilovic@levi9.com',18,'user'),
(112,'Petar Jovanovic','p.jovanovic@levi9.com',18,'user'),
(113,'Gabriel Patras','g.patras@levi9.com',19,'user'),
(114,'Iustinian Dominte','i.dominte@levi9.com',19,'user'),
(115,'Loredana Lehadus','l.lehadus@levi9.com',19,'user'),
(116,'Mihai Sitaru','m.sitaru@levi9.com',19,'user'),
(117,'Razvan Manole','r.manole@levi9.com',19,'user'),
(118,'Sorin Radu','s.radu@levi9.com',19,'user'),
(119,'Victor Munteanu','v.munteanu@levi9.com',19,'user'),
(120,'Petar Lalosevic','p.lalosevic@levi9.com',20,'user'),
(121,'Nikola Nikic','n.nikic@levi9.com',20,'user'),
(122,'Milan Savic','mi.savic@levi9.com',20,'user'),
(123,'Dusan Radovic','d.radovic@levi9.com',20,'user'),
(124,'Jelena Dubovi','j.dubovi@levi9.com',20,'user'),
(125,'Igor Dedic','i.dedic@levi9.com',20,'user'),
(126,'Nemanja Smiljanic','n.smiljanic@levi9.com',20,'user'),
(127,'Marijana Gligoric','m.gligoric@levi9.com',21,'user'),
(128,'Teodora Garasanin','t.garasanin@levi9.com',21,'user'),
(129,'Srdjan Ristanovic','s.ristanovic@levi9.com',21,'user'),
(130,'Ognjen Manevski','o.manevski@levi9.com',21,'user'),
(131,'Alexandra Mircea','a.mircea@levi9.com',22,'user'),
(132,'Ramona Farcas','r.farcas@levi9.com',22,'user'),
(133,'Lucian Ailenei','l.ailenei@levi9.com',22,'user'),
(134,'Ciprian Sofronia','c.sofronia@levi9.com',22,'user'),
(135,'Ionut Ovidiu Galatanu','i.galatanu@levi9.com',22,'user'),
(136,'Flavius Condrea','f.condrea@levi9.com',22,'user'),
(137,'Iulian Constantinescu','i.constantinescu@levi9.com',22,'user'),
(138,'Borislav Ervacanin','b.ervacanin@levi9.com',23,'user'),
(139,'Mirko Horvacki','m.horvacki@levi9.com',23,'user'),
(140,'Marko Mitic','m.mitic@levi9.com',23,'user'),
(141,'Simonida Kadic','s.kadic@levi9.com',23,'user'),
(142,'Djordje Filipovic','dj.filipovic@levi9.com',23,'user'),
(143,'Nina Bjelobaba','n.bjelobaba@levi9.com',23,'user'),
(144,'Ancuta Costan','a.costan@levi9.com',24,'user'),
(145,'Mariana Dumitriu','m.dumitriu@levi9.com',24,'user'),
(146,'Cristiana Antalut','c.antalut@levi9.com',24,'user'),
(147,'Radu Iscu','r.iscu@levi9.com',24,'user'),
(148,'Mircea Serediuc','m.serediuc@levi9.com',24,'user'),
(149,'Radu Vulpescu','r.vulpescu@levi9.com',24,'user'),
(150,'Constantin Oniga','c.oniga@levi9.com',24,'user'),
(151,'Sofija Bojic','s.bojic@levi9.com',25,'user'),
(152,'Goran Gizarovski','g.gizarovski@levi9.com',25,'user'),
(153,'Vanja Al-Halidi','v.al-halidi@levi9.com',25,'user'),
(154,'Zeljko Simic','z.simic@levi9.com',25,'user'),
(155,'Milan Urukalo','m.urukalo@levi9.com',25,'user'),
(156,'Boban Piskulic','b.piskulic@levi9.com',25,'user'),
(157,'Stanislav Ivanovic','s.ivanovic@levi9.com',26,'user'),
(158,'Slavko Bukvic','s.bukvic@levi9.com',26,'user'),
(159,'Bratislav Baljak','b.baljak@levi9.com',26,'user'),
(160,'Slobodan Dan','s.dan@levi9.com',26,'user'),
(161,'Zolt Varga','z.varga@levi9.com',26,'user'),
(162,'Dusan Munjiza','d.munjiza@levi9.com',26,'user'),
(163,'Oleksandr Odarchenko','o.odarchenko@levi9.com',27,'user'),
(164,'Orest Borovyi','o.borovyi@levi9.com',27,'user'),
(165,'Roman Datsyuk','r.datsyuk@levi9.com',27,'user'),
(166,'Yuriy Hulpa','y.hulpa@levi9.com',27,'user'),
(167,'Mykhailo Shchetinin','m.shchetinin@levi9.com',27,'user'),
(168,'Andrii Dumyn','a.dumyn@levi9.com',27,'user'),
(169,'Yevhen Sirotin','y.sirotin@levi9.com',28,'user'),
(170,'Roman Solodkyi','r.solodkyi@levi9.com',28,'user'),
(171,'Viktoria Golieusova','v.golieusova@levi9.com',28,'user'),
(172,'Aliia Ibragimova','a.ibragimova@levi9.com',28,'user'),
(173,'Oleh Fedianovych','o.fedianovych@levi9.com',28,'user'),
(174,'Mark Salabutin','m.salabutin@levi9.com',28,'user'),
(175,'Maksym Penderuk','m.penderuk@levi9.com',28,'user'),
(176,'Roman Kniazevych','r.kniazevych@levi9.com',29,'user'),
(177,'Volodymyr Shalimov','v.shalimov@levi9.com',29,'user'),
(178,'Oleh Koval','o.koval@levi9.com',29,'user'),
(179,'Mykhailo Kaminetskyi','m.kaminetskyi@levi9.com',29,'user'),
(180,'Roman Vitruk','r.vitruk@levi9.com',29,'user'),
(181,'Iulia Sargu','i.sargu@levi9.com',30,'user'),
(182,'Teodora Elena Timcu','t.timcu@levi9.com',30,'user'),
(183,'Adrian Ghitu','a.ghitu@levi9.com',30,'user'),
(184,'Marius Mihai Nastase','m.nastase@levi9.com',30,'user'),
(185,'Bianca Iuliana Bulai','b.bulai@levi9.com',30,'user'),
(186,'Andrei Pintilie','a.pintilie@levi9.com',30,'user'),
(187,'Dragos Tiganescu','d.tiganescu@levi9.com',30,'user'),
(188,'Aleksandar Gradina','a.gradina@levi9.com',31,'user'),
(189,'Boban Poznanovic','b.poznanovic@levi9.com',31,'user'),
(190,'Davor Ceman','d.ceman@levi9.com',31,'user'),
(191,'Miroslav Kospic','m.kospic@levi9.com',31,'user'),
(192,'Nikola Janicijevic','n.janicijevic@levi9.com',31,'user'),
(193,'Nikola Kolosnjaji','n.kolosnjaji@levi9.com',31,'user'),
(194,'Nikola Milic','n.milic@levi9.com',31,'user'),
(195,'Djordje Kalanj','dj.kalanj@levi9.com',32,'user'),
(196,'Sasa Malezic','s.malezic@levi9.com',32,'user'),
(197,'Marko Bradonjic','m.bradonjic@levi9.com',32,'user'),
(198,'Vidak Kavedzic','v.kavedzic@levi9.com',32,'user'),
(199,'Nikola Milinkovic','n.milinkovic@levi9.com',32,'user'),
(200,'Nikola B Nedeljkovic','nb.nedeljkovic@levi9.com',32,'user'),
(201,'Aleksandar Krstic','al.krstic@levi9.com',33,'user'),
(202,'Miro Kalajdzic','m.kalajdzic@levi9.com',33,'user'),
(203,'Vladan Vojimirovic','v.vojimirovic@levi9.com',33,'user'),
(204,'Nemanja Gladovic','n.gladovic@levi9.com',33,'user'),
(205,'Nenad Domuz','n.domuz@levi9.com',33,'user'),
(206,'Stefan Krstic','s.krstic@levi9.com',33,'user');
