INSERT INTO `team` VALUES
(1,'dev009',NULL,0.000,'aws','eu-west-1','ready'),
(2,'Epic Decomposition',NULL,0.000,'aws','eu-west-1','ready'),
(3,'Cloud Unicorns ',NULL,0.000,'azure','West US 2','ready'),
(4,'It works on my cloud',NULL,0.000,'aws','eu-west-1','ready'),
(5,'No Could for Old Men',NULL,0.000,'azure','West US 2','ready'),
(6,'Teledvabisi',NULL,0.000,'aws','eu-west-1','ready'),
(7,'J-AWS Team',NULL,0.000,'aws','eu-west-1','ready'),
(8,'Fluffy Unicorns',NULL,0.000,'aws','eu-west-1','ready'),
(9,'The Cookie Byte',NULL,0.000,'aws','eu-west-1','ready'),
(10,'Stroopwafel and Coffee',NULL,0.000,'azure','West US 2','ready'),
(11,'ForCryingOutCloud',NULL,0.000,'azure','West US 2','ready'),
(12,'noname?!',NULL,0.000,'aws','eu-west-1','ready'),
(13,'Karlovi Talenti',NULL,0.000,'azure','West US 2','ready'),
(14,'Mech''Clouds',NULL,0.000,'aws','eu-west-1','ready'),
(15,'BE-ton',NULL,0.000,'aws','eu-west-1','ready'),
(16,'cAPItans',NULL,0.000,'aws','eu-west-1','ready'),
(17,'Contractless',NULL,0.000,'aws','eu-west-1','ready'),
(18,'Kendo Masters Extreme ',NULL,0.000,'azure','West US 2','ready'),
(19,'Mali Mravi',NULL,0.000,'aws','eu-west-1','ready'),
(20,'Speed''n''Cloud',NULL,0.000,'aws','eu-west-1','ready'),
(21,'WYSIWYG’s',NULL,0.000,'aws','eu-west-1','ready'),
(22,'MobileZ',NULL,0.000,'aws','eu-west-1','ready'),
(23,'W-team ',NULL,0.000,'aws','eu-west-1','ready'),
(24,'Rockstars',NULL,0.000,'azure','West US 2','ready'),
(25,'Much Speed Such Service',NULL,0.000,'azure','West US 2','ready'),
(26,'Hahaton',NULL,0.000,'aws','eu-west-1','ready'),
(27,'Season Salad',NULL,0.000,'azure','West US 2','ready'),
(28,'JustAnotherTeam',NULL,0.000,'aws','eu-west-1','ready'),
(29,'hAPI9',NULL,0.000,'aws','eu-west-1','ready'),
(30,'noname again?',NULL,0.000,'aws','eu-west-1','ready'),
(31,'Mix & Fix',NULL,0.000,'azure','West US 2','ready'),
(32,'UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS',NULL,0.000,'aws','eu-west-1','ready'),
(33,'Frontpage',NULL,0.000,'azure','West US 2','ready'),
(34,'MS Haccess',NULL,0.000,'azure','West US 2','ready'),
(35,'Judges','https://rryr2ini4g.execute-api.us-east-1.amazonaws.com/dev',0.000,'aws','eu-west-1','ready');

INSERT INTO `user` VALUES
(1,'Miloš Jovanović','m.jovanovic@levi9.com',35,'admin'),
(2,'Dragan Gajić','d.gajic@levi9.com',35,'admin'),
(3,'Nikola Milutinović','n.milutinovic@levi9.com',35,'admin'),
(4,'Dragana Momčilović','d.momcilovic@levi9.com',35,'admin'),
(5,'Mirjana Kolarov','mi.kolarov@levi9.com',35,'admin'),
(6,'Dmytro Panin','d.panin@levi9.com',35,'admin'),
(7,'Ionut Stanescu','i.stanescu@levi9.com',35,'admin'),
(8,'Milos Radojcic','m.radojcic@levi9.com',1,'user'),
(9,'Mateja Asanin','m.asanin@levi9.com',1,'user'),
(10,'Milos Milutinovic','m.milutinovic@levi9.com',1,'user'),
(11,'Nikola Komazec','n.komazec@levi9.com',1,'user'),
(12,'Milica Panic','m.panic@levi9.com',1,'user'),
(13,'Vladimir Cepulja','v.crepulja@levi9.com',1,'user');
